<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HeroShopAPI.Business\HeroShopAPI.Business.csproj" />
    <ProjectReference Include="..\HeroShopAPI.Common\HeroShopAPI.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Resources\Images\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Resources\Images\backpack.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\Resources\Images\health_potion.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\Resources\Images\mysterious_satchel.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\Resources\Images\potion.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\Resources\Images\scroll.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\Resources\Images\short_sword.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\Resources\Images\spellbook.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\Resources\Images\wizards_hat.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
